FROM balenalib/%%BALENA_MACHINE_NAME%%-ubuntu-python:3.6-bionic-run


WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y build-essential python3-pil 

RUN pip3 install flask boto3


COPY not.py .

CMD [ "python3", "not.py" ]
